# -*- coding: utf-8 -*-
"""project_image_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNsEYXkjhC3uVLTBOSWzrfrYAEuLuDWZ
"""

!git clone https://github.com/EscVM/OIDv4_ToolKit.git

!cd OIDv4_ToolKit && pip install -r requirements.txt

!cd OIDv4_ToolKit && python main.py -h

!cd OIDv4_ToolKit && python3 main.py downloader --Dataset /content --classes Car Airplane Boat --type_csv train --limit 200

from fastai.vision.all import *
from ipywidgets import widgets

# path
path = Path('train')
#files
fls = get_image_files(path)
# yuklanmagan fayllar korish
failed = verify_images(path)

transports = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    get_items = get_image_files,
    splitter = RandomSplitter(valid_pct=0.2, seed=42),
    get_y = parent_label,
    item_tfms=Resize(224)
)

dls = transports.dataloaders(path)

dls.train.show_batch(max_n=32, nrows=4)

learn = cnn_learner(dls, resnet34, metrics=accuracy)
learn.fine_tune(4)

interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix()

interp.plot_top_losses(5, nrows=1)

upload = widgets.FileUpload()
upload

img = PILImage.create(upload.data[-1])
pred, pred_id, probs = learn.predict(img)
print(f'Prediction : {pred}')
print(f'Probability : {probs[pred_id]*100:.2f}%')
img

learn.export('transport_model.pkl')

model = load_learner('/content/transport_model.pkl')





